var main_enitity_items = {
    'CreativeWork': [
        {value: '', name: ''},
        {value: "Article", name: "Article"},
            {value: "BlogPosting", name: "&nbsp;&nbsp;&nbsp;&nbsp;BlogPosting"},
            {value: "NewsArticle", name: "&nbsp;&nbsp;&nbsp;&nbsp;NewsArticle"},
            {value: "Report", name: "&nbsp;&nbsp;&nbsp;&nbsp;Report"},
            {value: "ScholarlyArticle", name: "&nbsp;&nbsp;&nbsp;&nbsp;ScholarlyArticle"},
            {value: "SocialMediaPosting", name: "&nbsp;&nbsp;&nbsp;&nbsp;SocialMediaPosting"},
            {value: "TechArticle", name: "&nbsp;&nbsp;&nbsp;&nbsp;TechArticle"},
        {value: "Blog", name: "Blog"},
        {value: "Book", name: "Book"},
            {value: "Audiobook", name: "&nbsp;&nbsp;&nbsp;&nbsp;Audiobook"},
        {value: "Clip", name: "Clip"},
            {value: "MovieClip", name: "&nbsp;&nbsp;&nbsp;&nbsp;MovieClip"},
            {value: "RadioClip", name: "&nbsp;&nbsp;&nbsp;&nbsp;RadioClip"},
            {value: "TVClip", name: "&nbsp;&nbsp;&nbsp;&nbsp;TVClip"},
            {value: "VideoGameClip", name: "&nbsp;&nbsp;&nbsp;&nbsp;VideoGameClip"},
        {value: "Comment", name: "Comment"},
        {value: "Conversation", name: "Conversation"},
        {value: "CreativeWorkSeason", name: "CreativeWorkSeason"},
            {value: "RadioSeason", name: "&nbsp;&nbsp;&nbsp;&nbsp;RadioSeason"},
            {value: "TVSeason", name: "&nbsp;&nbsp;&nbsp;&nbsp;TVSeason"},
        {value: "CreativeWorkSeries", name: "CreativeWorkSeries"},
            {value: "BookSeries", name: "&nbsp;&nbsp;&nbsp;&nbsp;BookSeries"},
            {value: "MovieSeries", name: "&nbsp;&nbsp;&nbsp;&nbsp;MovieSeries"},
            {value: "Periodical", name: "&nbsp;&nbsp;&nbsp;&nbsp;Periodical"},
            {value: "RadioSeries", name: "&nbsp;&nbsp;&nbsp;&nbsp;RadioSeries"},
            {value: "TVSeries", name: "&nbsp;&nbsp;&nbsp;&nbsp;TVSeries"},
            {value: "VideoGameSeries", name: "&nbsp;&nbsp;&nbsp;&nbsp;VideoGameSeries"},
        {value: "DataCatalog", name: "DataCatalog"},
        {value: "Dataset", name: "Dataset"},
            {value: "Datafeed", name: "&nbsp;&nbsp;&nbsp;&nbsp;Datafeed"},
        {value: "DigitalDocument", name: "DigitalDocument"},
            {value: "NoteDigitalDocument", name: "&nbsp;&nbsp;&nbsp;&nbsp;NoteDigitalDocument"},
            {value: "PresentationDigitalDocument", name: "&nbsp;&nbsp;&nbsp;&nbsp;PresentationDigitalDocument"},
            {value: "SpreadsheetDigitalDocument", name: "&nbsp;&nbsp;&nbsp;&nbsp;SpreadsheetDigitalDocument"},
            {value: "TextDigitalDocument", name: "&nbsp;&nbsp;&nbsp;&nbsp;TextDigitalDocument"},
        {value: "Episode", name: "Episode"},
            {value: "RadioEpisode", name: "&nbsp;&nbsp;&nbsp;&nbsp;RadioEpisode"},
            {value: "TVEpisode", name: "&nbsp;&nbsp;&nbsp;&nbsp;TVEpisode"},
        {value: "Game", name: "Game"},
            {value: "VideoGame", name: "&nbsp;&nbsp;&nbsp;&nbsp;VideoGame"},
        {value: "Map", name: "Map"},
        {value: "MediaObject", name: "MediaObject"},
            {value: "AudioObject", name: "&nbsp;&nbsp;&nbsp;&nbsp;AudioObject"},
            {value: "DataDownload", name: "&nbsp;&nbsp;&nbsp;&nbsp;DataDownload"},
            {value: "ImageObject", name: "&nbsp;&nbsp;&nbsp;&nbsp;ImageObject"},
            {value: "MusicVideoObject", name: "&nbsp;&nbsp;&nbsp;&nbsp;MusicVideoObject"},
            {value: "VideoObject", name: "&nbsp;&nbsp;&nbsp;&nbsp;VideoObject"},
        {value: "Message", name: "Message"},
            {value: "EmailMessage", name: "&nbsp;&nbsp;&nbsp;&nbsp;EmailMessage"},
        {value: "Movie", name: "Movie"},
        {value: "MusicComposition", name: "MusicComposition"},
        {value: "MusicPlaylist", name: "MusicPlaylist"},
            {value: "MusicAlbum", name: "&nbsp;&nbsp;&nbsp;&nbsp;MusicAlbum"},
            {value: "MusicRelease", name: "&nbsp;&nbsp;&nbsp;&nbsp;MusicRelease"},
        {value: "MusicRecording", name: "MusicRecording"},
        {value: "Painting", name: "Painting"},
        {value: "Photograph", name: "Photograph"},
        {value: "PublicationIssue", name: "PublicationIssue"},
            {value: "ComicIssue", name: "&nbsp;&nbsp;&nbsp;&nbsp;ComicIssue"},
        {value: "PublicationVolume", name: "PublicationVolume"},
        {value: "Question", name: "Question"},
        {value: "Recipe", name: "Recipe"},
        {value: "Review", name: "Review"},
            {value: "ClaimReview", name: "&nbsp;&nbsp;&nbsp;&nbsp;ClaimReview"},
        {value: "Sculpture", name: "Sculpture"},
        {value: "Series", name: "Series"},
        {value: "SoftwareApplication", name: "SoftwareApplication"},
            {value: "MobileApplication", name: "&nbsp;&nbsp;&nbsp;&nbsp;MobileApplication"},
            {value: "VideoGame", name: "&nbsp;&nbsp;&nbsp;&nbsp;VideoGame"},
            {value: "WebApplication", name: "&nbsp;&nbsp;&nbsp;&nbsp;WebApplication"},
        {value: "SoftwareSourceCode", name: "SoftwareSourceCode"},
        {value: "TVSeason", name: "TVSeason"},
        {value: "TVSeries", name: "TVSeries"},
        {value: "VisualArtwork", name: "VisualArtwork"},
            {value: "CoverArt", name: "&nbsp;&nbsp;&nbsp;&nbsp;CoverArt"},
        {value: "WebPage", name: "WebPage"},
            {value: "AboutPage", name: "&nbsp;&nbsp;&nbsp;&nbsp;AboutPage"},
            {value: "CheckoutPage", name: "&nbsp;&nbsp;&nbsp;&nbsp;CheckoutPage"},
            {value: "CollectionPage", name: "&nbsp;&nbsp;&nbsp;&nbsp;CollectionPage"},
            {value: "ContactPage", name: "&nbsp;&nbsp;&nbsp;&nbsp;ContactPage"},
            {value: "ItemPage", name: "&nbsp;&nbsp;&nbsp;&nbsp;ItemPage"},
            {value: "MedicalWebPage", name: "&nbsp;&nbsp;&nbsp;&nbsp;MedicalWebPage"},
            {value: "ProfilePage", name: "&nbsp;&nbsp;&nbsp;&nbsp;ProfilePage"},
            {value: "QAPage", name: "&nbsp;&nbsp;&nbsp;&nbsp;QAPage"},
            {value: "SearchResultsPage", name: "&nbsp;&nbsp;&nbsp;&nbsp;SearchResultsPage"},
        ],
    'Event': [
        {value: '', name: ''},
        {value: "BusinessEvent", name: "BusinessEvent"},
        {value: "ChildrensEvent", name: "ChildrensEvent"},
        {value: "ComedyEvent", name: "ComedyEvent"},
        {value: "CourseInstance", name: "CourseInstance"},
        {value: "DanceEvent", name: "DanceEvent"},
        {value: "DeliveryEvent", name: "DeliveryEvent"},
        {value: "EducationEvent", name: "EducationEvent"},
        {value: "ExhibitionEvent", name: "ExhibitionEvent"},
        {value: "EventSeries", name: "EventSeries"},
        {value: "Festival", name: "Festival"},
        {value: "FoodEvent", name: "FoodEvent"},
        {value: "LiteraryEvent", name: "LiteraryEvent"},
        {value: "MusicEvent", name: "MusicEvent"},
        {value: "PublicationEvent", name: "PublicationEvent"},
        {value: "SaleEvent", name: "SaleEvent"},
        {value: "ScreeningEvent", name: "ScreeningEvent"},
        {value: "SocialEvent", name: "SocialEvent"},
        {value: "SportsEvent", name: "SportsEvent"},
        {value: "TheaterEvent", name: "TheaterEvent"},
        {value: "VisualArtsEvent", name: "VisualArtsEvent"},
        ],
    'Organization': [
        {value: '', name: ''},
        {value: "Airline", name: "Airline"},
        {value: "Corporation", name: "Corporation"},
        {value: "EducationalOrganization", name: "EducationalOrganization"},
            {value:'CollegeOrUniversity', name: '&nbsp;&nbsp;&nbsp;&nbsp;College Or University'},
            {value:'ElementarySchool', name: '&nbsp;&nbsp;&nbsp;&nbsp;Elementary School'},
            {value:'HighSchool', name: '&nbsp;&nbsp;&nbsp;&nbsp;High School'},
            {value:'MiddleSchool', name: '&nbsp;&nbsp;&nbsp;&nbsp;Middle School'},
            {value:'Preschool', name: '&nbsp;&nbsp;&nbsp;&nbsp;Preschool'},
            {value:'School', name: '&nbsp;&nbsp;&nbsp;&nbsp;School'},
        {value: "GovernmentOrganization", name: "Government Organization"},
        {value: "LocalBusiness", name: "Local Business"},
            {value: 'AnimalShelter', name: '&nbsp;&nbsp;&nbsp;&nbsp;Animal Shelter'},
            {value: 'AutomotiveBusiness', name: '&nbsp;&nbsp;&nbsp;&nbsp;Automotive Business'},
            {value: 'AutoBodyShop', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Auto Body Shop'},
            {value: 'AutoDealer', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Auto Dealer'},
            {value: 'AutoPartsStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Auto Parts Store'},
            {value: 'AutoRental', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Auto Rental'},
            {value: 'AutoRepair', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Auto Repair'},
            {value: 'AutoWash', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Auto Wash'},
            {value: 'GasStation', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Gas Station'},
            {value: 'MotorcycleDealer', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Motorcycle Dealer'},
            {value: 'MotorcycleRepair', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Motorcycle Repair'},
            {value: 'ChildCare', name: '&nbsp;&nbsp;&nbsp;&nbsp;Child Care'},
            {value: 'DryCleaningOrLaundry', name: '&nbsp;&nbsp;&nbsp;&nbsp;Dry Cleaning Or Laundry'},
            {value: 'EmergencyService', name: '&nbsp;&nbsp;&nbsp;&nbsp;Emergency Service'},
            {value: 'FireStation', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Fire Station'},
            {value: 'Hospital', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Hospital'},
            {value: 'PoliceStation', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Police Station'},
            {value: 'EmploymentAgency', name: '&nbsp;&nbsp;&nbsp;&nbsp;Employment Agency'},
            {value: 'EntertainmentBusiness', name: '&nbsp;&nbsp;&nbsp;&nbsp;Entertainment Business'},
            {value: 'AdultEntertainment', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Adult Entertainment'},
            {value: 'AmusementPark', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Amusement Park'},
            {value: 'ArtGallery', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Art Gallery'},
            {value: 'Casino', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Casino'},
            {value: 'ComedyClub', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Comedy Club'},
            {value: 'MovieTheater', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Movie Theater'},
            {value: 'NightClub', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Night Club'},
            {value: 'FinancialService', name: '&nbsp;&nbsp;&nbsp;&nbsp;Financial Service'},
            {value: 'AccountingService', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Accounting Service'},
            {value: 'AutomatedTeller', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Automated Teller'},
            {value: 'BankOrCreditUnion', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Bank Or Credit Union'},
            {value: 'InsuranceAgency', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Insurance Agency'},
            {value: 'FoodEstablishment', name: '&nbsp;&nbsp;&nbsp;&nbsp;Food Establishment'},
            {value: 'Bakery', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Bakery'},
            {value: 'BarOrPub', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Bar Or Pub'},
            {value: 'Brewery', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Brewery'},
            {value: 'CafeOrCoffeeShop', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cafe Or Coffee Shop'},
            {value: 'FastFoodRestaurant', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Fast Food Restaurant'},
            {value: 'IceCreamShop', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ice Cream Shop'},
            {value: 'Restaurant', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Restaurant'},
            {value: 'Winery', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Winery'},
            {value: 'GovernmentOffice', name: '&nbsp;&nbsp;&nbsp;&nbsp;Government Office'},
            {value: 'PostOffice', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Post Office'},
            {value: 'HealthAndBeautyBusiness', name: '&nbsp;&nbsp;&nbsp;&nbsp;Health And Beauty Business'},
            {value: 'BeautySalon', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Beauty Salon'},
            {value: 'DaySpa', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Day Spa'},
            {value: 'HairSalon', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Hair Salon'},
            {value: 'HealthClub', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Health Club'},
            {value: 'NailSalon', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Nail Salon'},
            {value: 'TattooParlor', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tattoo Parlor'},
            {value: 'HomeAndConstructionBusiness', name: '&nbsp;&nbsp;&nbsp;&nbsp;Home And Construction Business'},
            {value: 'Electrician', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Electrician'},
            {value: 'GeneralContractor', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;General Contractor'},
            {value: 'HVACBusiness', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;HVAC Business'},
            {value: 'HousePainter', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;House Painter'},
            {value: 'Locksmith', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Locksmith'},
            {value: 'MovingCompany', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Moving Company'},
            {value: 'Plumber', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Plumber'},
            {value: 'RoofingContractor', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Roofing Contractor'},
            {value: 'InternetCafe', name: '&nbsp;&nbsp;&nbsp;&nbsp;Internet Cafe'},
            {value: 'LegalService', name: '&nbsp;&nbsp;&nbsp;&nbsp;Legal Service'},
            {value: 'Attorney', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Attorney'},
            {value: 'Notary', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Notary'},
            {value: 'Library', name: '&nbsp;&nbsp;&nbsp;&nbsp;Library'},
            {value: 'LodgingBusiness', name: '&nbsp;&nbsp;&nbsp;&nbsp;Lodging Business'},
            {value: 'BedAndBreakfast', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Bed And Breakfast'},
            {value: 'Hostel', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Hostel'},
            {value: 'Hotel', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Hotel'},
            {value: 'Motel', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Motel'},
            {value: 'MedicalOrganization', name: '&nbsp;&nbsp;&nbsp;&nbsp;Medical Organization'},
            {value: 'Dentist', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Dentist'},
            {value: 'DiagnosticLab', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Diagnostic Lab'},
            {value: 'Hospital', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Hospital'},
            {value: 'MedicalClinic', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Medical Clinic'},
            {value: 'Optician', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Optician'},
            {value: 'Pharmacy', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Pharmacy'},
            {value: 'Physician', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Physician'},
            {value: 'VeterinaryCare', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Veterinary Care'},
            {value: 'ProfessionalService', name: '&nbsp;&nbsp;&nbsp;&nbsp;Professional Service'},
            {value: 'RadioStation', name: '&nbsp;&nbsp;&nbsp;&nbsp;Radio Station'},
            {value: 'RealEstateAgent', name: '&nbsp;&nbsp;&nbsp;&nbsp;Real Estate Agent'},
            {value: 'RecyclingCenter', name: '&nbsp;&nbsp;&nbsp;&nbsp;Recycling Center'},
            {value: 'SelfStorage', name: '&nbsp;&nbsp;&nbsp;&nbsp;Self Storage'},
            {value: 'ShoppingCenter', name: '&nbsp;&nbsp;&nbsp;&nbsp;Shopping Center'},
            {value: 'SportsActivityLocation', name: '&nbsp;&nbsp;&nbsp;&nbsp;Sports Activity Location'},
            {value: 'BowlingAlley', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Bowling Alley'},
            {value: 'ExerciseGym', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Exercise Gym'},
            {value: 'GolfCourse', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Golf Course'},
            {value: 'HealthClub', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Health Club'},
            {value: 'PublicSwimmingPool', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Public Swimming Pool'},
            {value: 'SkiResort', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ski Resort'},
            {value: 'SportsClub', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Sports Club'},
            {value: 'StadiumOrArena', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Stadium Or Arena'},
            {value: 'TennisComplex', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tennis Complex'},
            {value: 'Store', name: '&nbsp;&nbsp;&nbsp;&nbsp;Store'},
            {value: 'AutoPartsStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Auto Parts Store'},
            {value: 'BikeStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Bike Store'},
            {value: 'BookStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Book Store'},
            {value: 'ClothingStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Clothing Store'},
            {value: 'ComputerStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Computer Store'},
            {value: 'ConvenienceStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Convenience Store'},
            {value: 'DepartmentStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Department Store'},
            {value: 'ElectronicsStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Electronics Store'},
            {value: 'Florist', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Florist'},
            {value: 'FurnitureStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Furniture Store'},
            {value: 'GardenStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Garden Store'},
            {value: 'GroceryStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Grocery Store'},
            {value: 'HardwareStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Hardware Store'},
            {value: 'HobbyShop', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Hobby Shop'},
            {value: 'HomeGoodsStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Home Goods Store'},
            {value: 'JewelryStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Jewelry Store'},
            {value: 'LiquorStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Liquor Store'},
            {value: 'MensClothingStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Mens Clothing Store'},
            {value: 'MobilePhoneStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Mobile Phone Store'},
            {value: 'MovieRentalStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Movie Rental Store'},
            {value: 'MusicStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Music Store'},
            {value: 'OfficeEquipmentStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Office Equipment Store'},
            {value: 'OutletStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Outlet Store'},
            {value: 'PawnShop', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Pawn Shop'},
            {value: 'PetStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Pet Store'},
            {value: 'ShoeStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Shoe Store'},
            {value: 'SportingGoodsStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Sporting Goods Store'},
            {value: 'TireShop', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tire Shop'},
            {value: 'ToyStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Toy Store'},
            {value: 'WholesaleStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Wholesale Store'},
            {value: 'TelevisionStation', name: '&nbsp;&nbsp;&nbsp;&nbsp;Television Station'},
            {value: 'TouristInformationCenter', name: '&nbsp;&nbsp;&nbsp;&nbsp;Tourist Information Center'},
            {value: 'TravelAgency', name: '&nbsp;&nbsp;&nbsp;&nbsp;Travel Agency'},
        {value: "NGO", name: "NGO"},
        {value: "PerformingGroup", name: "Performing Group"},
            {value:'DanceGroup', name: '&nbsp;&nbsp;&nbsp;&nbsp;Dance Group'},
            {value:'MusicGroup', name: '&nbsp;&nbsp;&nbsp;&nbsp;Music Group'},
            {value:'TheaterGroup', name: '&nbsp;&nbsp;&nbsp;&nbsp;Theater Group'},
        {value: "SportsOrganization", name: "Sports Organization"},
            {value:'SportsTeam', name: '&nbsp;&nbsp;&nbsp;&nbsp;Sports Team'},
        ],
    'Person': [
        {value: '', name: ''},
        {value: "Patient", name: "Patient"},
        ],
    'Product': [
        {value: '', name: ''},
        {value: "IndividualProduct", name: "IndividualProduct"},
        {value: "ProductModel", name: "ProductModel"},
        {value: "SomeProducts", name: "SomeProducts"},
        {value: "Vehicle", name: "Vehicle"},
        ],
    };
