var items = {
    'Airline':  [
        {value: '', name: ''},
        ],
    'Corporation': [
        {value: '', name: ''},
        ],
    'EducationalOrganization': [
        {name: '', value:''},
        {name: 'College Or University', value:'CollegeOrUniversity'},
        {name: 'Elementary School', value:'ElementarySchool'},
        {name: 'High School', value:'HighSchool'},
        {name: 'Middle School', value:'MiddleSchool'},
        {name: 'Preschool', value:'Preschool'},
        {name: 'School', value:'School'},
        ],
    'GovernmentOrganization': [
        {value: '', name: ''},
        ],
    'LocalBusiness': [
        {value: '', name: ''},
        {value: 'AnimalShelter', name: 'Animal Shelter'},
        {value: 'AutomotiveBusiness', name: 'Automotive Business'},
        {value: 'AutoBodyShop', name: '&nbsp;&nbsp;&nbsp;&nbsp;Auto Body Shop'},
        {value: 'AutoDealer', name: '&nbsp;&nbsp;&nbsp;&nbsp;Auto Dealer'},
        {value: 'AutoPartsStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;Auto Parts Store'},
        {value: 'AutoRental', name: '&nbsp;&nbsp;&nbsp;&nbsp;Auto Rental'},
        {value: 'AutoRepair', name: '&nbsp;&nbsp;&nbsp;&nbsp;Auto Repair'},
        {value: 'AutoWash', name: '&nbsp;&nbsp;&nbsp;&nbsp;Auto Wash'},
        {value: 'GasStation', name: '&nbsp;&nbsp;&nbsp;&nbsp;Gas Station'},
        {value: 'MotorcycleDealer', name: '&nbsp;&nbsp;&nbsp;&nbsp;Motorcycle Dealer'},
        {value: 'MotorcycleRepair', name: '&nbsp;&nbsp;&nbsp;&nbsp;Motorcycle Repair'},
        {value: 'ChildCare', name: 'Child Care'},
        {value: 'DryCleaningOrLaundry', name: 'Dry Cleaning Or Laundry'},
        {value: 'EmergencyService', name: 'Emergency Service'},
        {value: 'FireStation', name: '&nbsp;&nbsp;&nbsp;&nbsp;Fire Station'},
        {value: 'Hospital', name: '&nbsp;&nbsp;&nbsp;&nbsp;Hospital'},
        {value: 'PoliceStation', name: '&nbsp;&nbsp;&nbsp;&nbsp;Police Station'},
        {value: 'EmploymentAgency', name: 'Employment Agency'},
        {value: 'EntertainmentBusiness', name: 'Entertainment Business'},
        {value: 'AdultEntertainment', name: '&nbsp;&nbsp;&nbsp;&nbsp;Adult Entertainment'},
        {value: 'AmusementPark', name: '&nbsp;&nbsp;&nbsp;&nbsp;Amusement Park'},
        {value: 'ArtGallery', name: '&nbsp;&nbsp;&nbsp;&nbsp;Art Gallery'},
        {value: 'Casino', name: '&nbsp;&nbsp;&nbsp;&nbsp;Casino'},
        {value: 'ComedyClub', name: '&nbsp;&nbsp;&nbsp;&nbsp;Comedy Club'},
        {value: 'MovieTheater', name: '&nbsp;&nbsp;&nbsp;&nbsp;Movie Theater'},
        {value: 'NightClub', name: '&nbsp;&nbsp;&nbsp;&nbsp;Night Club'},
        {value: 'FinancialService', name: 'Financial Service'},
        {value: 'AccountingService', name: '&nbsp;&nbsp;&nbsp;&nbsp;Accounting Service'},
        {value: 'AutomatedTeller', name: '&nbsp;&nbsp;&nbsp;&nbsp;Automated Teller'},
        {value: 'BankOrCreditUnion', name: '&nbsp;&nbsp;&nbsp;&nbsp;Bank Or Credit Union'},
        {value: 'InsuranceAgency', name: '&nbsp;&nbsp;&nbsp;&nbsp;Insurance Agency'},
        {value: 'FoodEstablishment', name: 'Food Establishment'},
        {value: 'Bakery', name: '&nbsp;&nbsp;&nbsp;&nbsp;Bakery'},
        {value: 'BarOrPub', name: '&nbsp;&nbsp;&nbsp;&nbsp;Bar Or Pub'},
        {value: 'Brewery', name: '&nbsp;&nbsp;&nbsp;&nbsp;Brewery'},
        {value: 'CafeOrCoffeeShop', name: '&nbsp;&nbsp;&nbsp;&nbsp;Cafe Or Coffee Shop'},
        {value: 'FastFoodRestaurant', name: '&nbsp;&nbsp;&nbsp;&nbsp;Fast Food Restaurant'},
        {value: 'IceCreamShop', name: '&nbsp;&nbsp;&nbsp;&nbsp;Ice Cream Shop'},
        {value: 'Restaurant', name: '&nbsp;&nbsp;&nbsp;&nbsp;Restaurant'},
        {value: 'Winery', name: '&nbsp;&nbsp;&nbsp;&nbsp;Winery'},
        {value: 'GovernmentOffice', name: 'Government Office'},
        {value: 'PostOffice', name: '&nbsp;&nbsp;&nbsp;&nbsp;Post Office'},
        {value: 'HealthAndBeautyBusiness', name: 'Health And Beauty Business'},
        {value: 'BeautySalon', name: '&nbsp;&nbsp;&nbsp;&nbsp;Beauty Salon'},
        {value: 'DaySpa', name: '&nbsp;&nbsp;&nbsp;&nbsp;Day Spa'},
        {value: 'HairSalon', name: '&nbsp;&nbsp;&nbsp;&nbsp;Hair Salon'},
        {value: 'HealthClub', name: '&nbsp;&nbsp;&nbsp;&nbsp;Health Club'},
        {value: 'NailSalon', name: '&nbsp;&nbsp;&nbsp;&nbsp;Nail Salon'},
        {value: 'TattooParlor', name: '&nbsp;&nbsp;&nbsp;&nbsp;Tattoo Parlor'},
        {value: 'HomeAndConstructionBusiness', name: 'Home And Construction Business'},
        {value: 'Electrician', name: '&nbsp;&nbsp;&nbsp;&nbsp;Electrician'},
        {value: 'GeneralContractor', name: '&nbsp;&nbsp;&nbsp;&nbsp;General Contractor'},
        {value: 'HVACBusiness', name: '&nbsp;&nbsp;&nbsp;&nbsp;HVAC Business'},
        {value: 'HousePainter', name: '&nbsp;&nbsp;&nbsp;&nbsp;House Painter'},
        {value: 'Locksmith', name: '&nbsp;&nbsp;&nbsp;&nbsp;Locksmith'},
        {value: 'MovingCompany', name: '&nbsp;&nbsp;&nbsp;&nbsp;Moving Company'},
        {value: 'Plumber', name: '&nbsp;&nbsp;&nbsp;&nbsp;Plumber'},
        {value: 'RoofingContractor', name: '&nbsp;&nbsp;&nbsp;&nbsp;Roofing Contractor'},
        {value: 'InternetCafe', name: 'Internet Cafe'},
        {value: 'LegalService', name: 'Legal Service'},
        {value: 'Attorney', name: '&nbsp;&nbsp;&nbsp;&nbsp;Attorney'},
        {value: 'Notary', name: '&nbsp;&nbsp;&nbsp;&nbsp;Notary'},
        {value: 'Library', name: 'Library'},
        {value: 'LodgingBusiness', name: 'Lodging Business'},
        {value: 'BedAndBreakfast', name: '&nbsp;&nbsp;&nbsp;&nbsp;Bed And Breakfast'},
        {value: 'Hostel', name: '&nbsp;&nbsp;&nbsp;&nbsp;Hostel'},
        {value: 'Hotel', name: '&nbsp;&nbsp;&nbsp;&nbsp;Hotel'},
        {value: 'Motel', name: '&nbsp;&nbsp;&nbsp;&nbsp;Motel'},
        {value: 'MedicalOrganization', name: 'Medical Organization'},
        {value: 'Dentist', name: '&nbsp;&nbsp;&nbsp;&nbsp;Dentist'},
        {value: 'DiagnosticLab', name: '&nbsp;&nbsp;&nbsp;&nbsp;Diagnostic Lab'},
        {value: 'Hospital', name: '&nbsp;&nbsp;&nbsp;&nbsp;Hospital'},
        {value: 'MedicalClinic', name: '&nbsp;&nbsp;&nbsp;&nbsp;Medical Clinic'},
        {value: 'Optician', name: '&nbsp;&nbsp;&nbsp;&nbsp;Optician'},
        {value: 'Pharmacy', name: '&nbsp;&nbsp;&nbsp;&nbsp;Pharmacy'},
        {value: 'Physician', name: '&nbsp;&nbsp;&nbsp;&nbsp;Physician'},
        {value: 'VeterinaryCare', name: '&nbsp;&nbsp;&nbsp;&nbsp;Veterinary Care'},
        {value: 'ProfessionalService', name: 'Professional Service'},
        {value: 'RadioStation', name: 'Radio Station'},
        {value: 'RealEstateAgent', name: 'Real Estate Agent'},
        {value: 'RecyclingCenter', name: 'Recycling Center'},
        {value: 'SelfStorage', name: 'Self Storage'},
        {value: 'ShoppingCenter', name: 'Shopping Center'},
        {value: 'SportsActivityLocation', name: 'Sports Activity Location'},
        {value: 'BowlingAlley', name: '&nbsp;&nbsp;&nbsp;&nbsp;Bowling Alley'},
        {value: 'ExerciseGym', name: '&nbsp;&nbsp;&nbsp;&nbsp;Exercise Gym'},
        {value: 'GolfCourse', name: '&nbsp;&nbsp;&nbsp;&nbsp;Golf Course'},
        {value: 'HealthClub', name: '&nbsp;&nbsp;&nbsp;&nbsp;Health Club'},
        {value: 'PublicSwimmingPool', name: '&nbsp;&nbsp;&nbsp;&nbsp;Public Swimming Pool'},
        {value: 'SkiResort', name: '&nbsp;&nbsp;&nbsp;&nbsp;Ski Resort'},
        {value: 'SportsClub', name: '&nbsp;&nbsp;&nbsp;&nbsp;Sports Club'},
        {value: 'StadiumOrArena', name: '&nbsp;&nbsp;&nbsp;&nbsp;Stadium Or Arena'},
        {value: 'TennisComplex', name: '&nbsp;&nbsp;&nbsp;&nbsp;Tennis Complex'},
        {value: 'Store', name: 'Store'},
        {value: 'AutoPartsStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;Auto Parts Store'},
        {value: 'BikeStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;Bike Store'},
        {value: 'BookStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;Book Store'},
        {value: 'ClothingStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;Clothing Store'},
        {value: 'ComputerStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;Computer Store'},
        {value: 'ConvenienceStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;Convenience Store'},
        {value: 'DepartmentStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;Department Store'},
        {value: 'ElectronicsStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;Electronics Store'},
        {value: 'Florist', name: '&nbsp;&nbsp;&nbsp;&nbsp;Florist'},
        {value: 'FurnitureStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;Furniture Store'},
        {value: 'GardenStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;Garden Store'},
        {value: 'GroceryStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;Grocery Store'},
        {value: 'HardwareStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;Hardware Store'},
        {value: 'HobbyShop', name: '&nbsp;&nbsp;&nbsp;&nbsp;Hobby Shop'},
        {value: 'HomeGoodsStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;Home Goods Store'},
        {value: 'JewelryStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;Jewelry Store'},
        {value: 'LiquorStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;Liquor Store'},
        {value: 'MensClothingStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;Mens Clothing Store'},
        {value: 'MobilePhoneStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;Mobile Phone Store'},
        {value: 'MovieRentalStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;Movie Rental Store'},
        {value: 'MusicStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;Music Store'},
        {value: 'OfficeEquipmentStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;Office Equipment Store'},
        {value: 'OutletStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;Outlet Store'},
        {value: 'PawnShop', name: '&nbsp;&nbsp;&nbsp;&nbsp;Pawn Shop'},
        {value: 'PetStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;Pet Store'},
        {value: 'ShoeStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;Shoe Store'},
        {value: 'SportingGoodsStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;Sporting Goods Store'},
        {value: 'TireShop', name: '&nbsp;&nbsp;&nbsp;&nbsp;Tire Shop'},
        {value: 'ToyStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;Toy Store'},
        {value: 'WholesaleStore', name: '&nbsp;&nbsp;&nbsp;&nbsp;Wholesale Store'},
        {value: 'TelevisionStation', name: 'Television Station'},
        {value: 'TouristInformationCenter', name: 'Tourist Information Center'},
        {value: 'TravelAgency', name: 'Travel Agency'},
        ],
    'NGO': [
        {value: '', name: ''},
        ],
    'PerformingGroup': [
        {name: '', value:''},
        {name: 'Dance Group', value:'DanceGroup'},
        {name: 'Music Group', value:'MusicGroup'},
        {name: 'Theater Group', value:'TheaterGroup'},
        ],
    'SportsOrganization': [
            {name: '', value:''},
            {name: 'Sports Team', value:'SportsTeam'},
        ],
    };